import { NextRequest, NextResponse } from 'next/server';
import { createServerSupabaseClient, createServiceRoleClient } from '@/lib/supabase/server';
import {
  exchangeCodeForTokens,
  getUserInfo,
  encryptTokens,
} from '@/lib/gmail/oauth';

export async function GET(request: NextRequest) {
  const searchParams = request.nextUrl.searchParams;
  const code = searchParams.get('code');
  const state = searchParams.get('state');
  const error = searchParams.get('error');

  const baseUrl = process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3001';

  // Handle OAuth errors
  if (error) {
    console.error('Gmail OAuth error:', error);
    return NextResponse.redirect(
      `${baseUrl}/connect-email?error=${encodeURIComponent(error)}`
    );
  }

  if (!code || !state) {
    return NextResponse.redirect(
      `${baseUrl}/connect-email?error=missing_parameters`
    );
  }

  try {
    // Verify state and extract user ID
    const decodedState = JSON.parse(Buffer.from(state, 'base64').toString());
    const { userId, timestamp } = decodedState;

    console.log('OAuth callback - userId from state:', userId);
    console.log('OAuth callback - timestamp:', timestamp);

    // Check state timestamp (expire after 10 minutes)
    if (Date.now() - timestamp > 10 * 60 * 1000) {
      return NextResponse.redirect(`${baseUrl}/connect-email?error=state_expired`);
    }

    // Try to verify user is still authenticated, but don't fail if session is lost during redirect
    const supabase = createServerSupabaseClient();
    const {
      data: { user },
    } = await supabase.auth.getUser();

    console.log('OAuth callback - authenticated user:', user?.id);

    // Use the userId from state if session check fails (state was generated by our server)
    const effectiveUserId = user?.id || userId;

    if (!effectiveUserId) {
      return NextResponse.redirect(`${baseUrl}/login?error=no_user`);
    }

    // Exchange code for tokens
    console.log('Exchanging code for tokens...');
    const tokens = await exchangeCodeForTokens(code);
    console.log('Tokens received successfully');

    // Get user's email from Google
    console.log('Getting user info from Google...');
    const googleUser = await getUserInfo(tokens.access_token);
    console.log('Google user email:', googleUser.email);

    // Encrypt tokens
    const { accessTokenEncrypted, refreshTokenEncrypted } = encryptTokens(tokens);
    console.log('Tokens encrypted');

    // Store email account in database
    const serviceClient = createServiceRoleClient();

    // First, ensure the user exists in our users table
    const { data: existingUser, error: userCheckError } = await serviceClient
      .from('users')
      .select('id')
      .eq('id', effectiveUserId)
      .single();

    console.log('User check:', existingUser, 'Error:', userCheckError?.message);

    if (!existingUser) {
      // Create user record
      console.log('Creating user record...');
      const { error: createUserError } = await serviceClient.from('users').insert({
        id: effectiveUserId,
        email: googleUser.email,
        full_name: googleUser.name,
        avatar_url: googleUser.picture,
      });

      if (createUserError) {
        console.error('Failed to create user:', createUserError.message);
        throw new Error(`Failed to create user: ${createUserError.message}`);
      }
      console.log('User created successfully');
    }

    // Check if email account already exists
    const { data: existingAccount, error: selectError } = await serviceClient
      .from('email_accounts')
      .select('id')
      .eq('user_id', effectiveUserId)
      .eq('email_address', googleUser.email)
      .single();

    console.log('Existing account check:', existingAccount, 'Error:', selectError?.message);

    if (existingAccount) {
      // Update existing account
      const { error: updateError } = await serviceClient
        .from('email_accounts')
        .update({
          access_token_encrypted: accessTokenEncrypted,
          refresh_token_encrypted: refreshTokenEncrypted,
          token_expires_at: new Date(tokens.expiry_date).toISOString(),
          scopes: tokens.scope.split(' '),
          is_active: true,
          updated_at: new Date().toISOString(),
        })
        .eq('id', existingAccount.id);

      console.log('Update result error:', updateError?.message);
    } else {
      // Create new account
      const { error: insertError } = await serviceClient.from('email_accounts').insert({
        user_id: effectiveUserId,
        email_address: googleUser.email,
        provider: 'gmail',
        access_token_encrypted: accessTokenEncrypted,
        refresh_token_encrypted: refreshTokenEncrypted,
        token_expires_at: new Date(tokens.expiry_date).toISOString(),
        scopes: tokens.scope.split(' '),
        is_active: true,
      });

      console.log('Insert result error:', insertError?.message);

      if (insertError) {
        throw new Error(`Failed to save email account: ${insertError.message}`);
      }

      // Also update user profile if name/avatar not set
      const { data: profile } = await serviceClient
        .from('users')
        .select('full_name, avatar_url')
        .eq('id', effectiveUserId)
        .single();

      if (profile && (!profile.full_name || !profile.avatar_url)) {
        await serviceClient
          .from('users')
          .update({
            full_name: profile.full_name || googleUser.name,
            avatar_url: profile.avatar_url || googleUser.picture,
          })
          .eq('id', effectiveUserId);
      }
    }

    console.log('About to redirect to inbox...');

    // Create audit log (don't fail if this errors)
    try {
      await serviceClient.from('audit_logs').insert({
        user_id: effectiveUserId,
        action: 'email_account_connected',
        entity_type: 'email_account',
        entity_id: existingAccount?.id || null,
        details: { email: googleUser.email },
      });
    } catch (auditErr) {
      console.error('Failed to create audit log:', auditErr);
    }

    // Redirect to inbox
    return NextResponse.redirect(`${baseUrl}/inbox?connected=true`);
  } catch (err: any) {
    console.error('Gmail OAuth callback error:', err);
    console.error('Error details:', err?.message, err?.stack);
    const errorMessage = encodeURIComponent(err?.message || 'callback_failed');
    return NextResponse.redirect(
      `${baseUrl}/connect-email?error=${errorMessage}`
    );
  }
}
